### ISSUE TITLE
error in CharacterInput.py

### ISSUE THREAD

**Issue by dmnfarrell** [valentinegarikayi/Getting-Started-#1]
I get this error when a name is submitted:

```
What is your name: damien
Traceback (most recent call last):
  File "CharacterInput.py", line 3, in <module>
    name = input('What is your name: ')
  File "<string>", line 1, in <module>
NameError: name 'damien' is not defined
```

**Comment by valentinegarikayi** [comment]
It works, please enter your name as string. Also how are you executing the script?

**Comment by dmnfarrell** [comment]
Ok it works. I was using python2.
The output is hard to read though!

**Comment by valentinegarikayi** [comment]
I will format the output and push the changes. Thats a good point you make!
